apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    config_items:
    - repos:
      - openeuler
      - src-openeuler
      - openeuler-competition
      - openeuler-compliance
      - openeuler-risc-v
      - openeuler-practice-courses
      - openeuler-customization
      - zengchen1024/openeuler-test
      excluded_repos:
      - openeuler/community
      labels_for_merge:
      - openeuler-cla/yes
      unable_checking_reviewer_for_pr: true
      freeze_file:
      - owner: openeuler
        repo: release-management
        branch: master
        path: release-management.yaml

    - repos:
      - openeuler/community
      check_permission_based_on_sig_owners: true
      sigs_dir: sig
      labels_for_merge:
      - openeuler-cla/yes
      unable_checking_reviewer_for_pr: true
      freeze_file:
      - owner: openeuler
        repo: release-management
        branch: master
        path: release-management.yaml
